### ISSUE TITLE
反馈和请教问题

### ISSUE THREAD

**Issue by jackywjzhao** [huangsir250/financial_data_pools#2]
有个小反馈哈:
1. 通过网易获取历史数据不知道为何有2-3天数据延时, 比如今天才能获取到Mar/24的数据，获取不到最新的数据(Mar/26)， 这个情况有什么好建议吗？
2. 另外运行好几个py,比如concepts_down.py都出现报错 RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods，查看自己的库里是已经安装的了，请指导怎么解决？
![error](https://user-images.githubusercontent.com/49721820/112715036-c0b4e600-8f18-11eb-8104-5238b9bafef7.jpg)

**Comment by huangsir250** [comment]
1、获取不到最新的数据是网易那边没有更新，可以换其他的地址源，其实网络上有很多的，比如tushare；
2、应该是你的pymysql包造成的问题，建议更新一下，python -m pip install PyMySQL[rsa]，更新的时候注意一下你的虚拟环境

**Comment by jackywjzhao** [comment]
谢谢Huangsir即使回复，由于本人是新手, 所以可能遇到的问题比较多，见谅！！

库的问题已经解决了
1. 换源的建议(tushare), 是否需要重新修改代码呢？每个源的数据组成可能不一样，你现在这个包是针对网易的还是都通用呢？
2. 就是保存数据的时候遇到错误，如图，求协助
![error1](https://user-images.githubusercontent.com/49721820/112743610-4a24f080-8fcb-11eb-9161-b25e4a1cb507.jpg)

![error](https://user-images.githubusercontent.com/49721820/112743589-25307d80-8fcb-11eb-8a91-efff02bd6471.jpg)

**Comment by huangsir250** [comment]
1.tushare需要修改代码，不过tushare需要积分，网易是免费的，网易有时候有时很及时的，不知道更新的规律是什么；
2.根据报错的信息，你应该没有把sql_create_tables里面的sql执行，建议先执行一遍后再爬取数据。现在的情况你可以删除已经存在的数据表或者重新建一个数据库，然后执行sql建表语句，修改conf.ini的数据库名。
