### ISSUE TITLE
龙虎榜里面的 b_sort 是啥？

### ISSUE THREAD

**Issue by binterminator** [huangsir250/financial_data_pools#4]
龙虎榜里面的 b_sort 是啥？
有 1 2 3 4 5 代表啥意思？
                        cursor.execute(
                            'insert into lhb(trade_date,item_code,item_name,b_sort,sc_name,buying,selling,sc_id,detail_type) '
                            'values(%s, %s, %s,%s,%s, %s, %s, %s, %s);',
                            (trade_date, item_code, item_name,b_sort, sc_name, buying, selling, sc_id, detail_type))

**Comment by huangsir250** [comment]
是买一买二买三买四买五的意思，这个要重构。
