### ISSUE TITLE
下载全量数据报错

### ISSUE THREAD

**Issue by jackywjzhao** [huangsir250/financial_data_pools#5]
huangsir, 运行修改后的代码报错: stock_zh_a_hist() got an unexpected keyword argument 'period'
![error_2021-09-18_11-44-17](https://user-images.githubusercontent.com/49721820/133871511-6a430d76-18cf-4c4d-915f-13b1faa42ef1.jpg)

**Comment by huangsir250** [comment]
好神奇，我自己的没有发现啥问题。你更新一下代码试试

**Comment by jackywjzhao** [comment]
现在重新安装好了，有个依赖可能需要跟新一下requirement的包，pyyaml, 谢谢啦！！
