### ISSUE TITLE
Tradedetail_down.py 

### ISSUE THREAD

**Issue by jackywjzhao** [huangsir250/financial_data_pools#6]
输出后的csv, 每个股票代码前面都加了; (save_df['股票代码'] = save_df['股票代码'].map(lambda x: ";" + x)
最后保存输出后变成下面这样，这个是有什么特别考虑和作用吗？

股票代码,股票名称,开盘,最高,最低,最新价,昨收,涨跌额,涨跌幅,成交量,成交额,振幅,换手率,市盈率,量比,流通市值,总市值
;688697,N纽威,28.0,29.44,22.31,22.47,7.55,14.92,197.62,478049,1161526112.0,94.44,71.94,53.17,,7340200749,1493102199
;605598,N港湾,16.64,19.97,16.64,19.97,13.87,6.1,43.98,10224,20387504.0,24.01,2.37,34.54,,3449687036,862573536

**Comment by huangsir250** [comment]
深交所主板这边0开头的代码会被截掉，比如000100,保存到文件的时候变成了100， 其他的类似

**Comment by jackywjzhao** [comment]
谢谢解释，清楚了没有问题，辛苦啦！！
